### ISSUE TITLE
Add better documentation please

### ISSUE THREAD

**Issue by michaelpb** [sdbeng/sdb-module#1]
I'm not sure how to run this as is.

Could you update the README?

Thanks.

**Comment by michaelpb** [comment]
I'm trying to run

```
var sdbmod = require('sdb-module');
```

but it doesnt do what I expect.

What am I doing wrong?

**Comment by sdbeng** [comment]
Good call Michael! Readme is now updated and code fixed. 
Steps: 
- make a new directory and run
`npm init -y` 

- create your app.js to request the module.

`const greeter = require("sdb-module)`
`console.log(greeter())`

- Then you have the option to install it globally 
`npm i -g sdb-module`

and run it with:
`$greeter --name "Mike"`
should get Hello Mike

👍
